### ISSUE TITLE
Make cluster more resilient by ignoring non-existing resources on deletion

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#102]
When we're deleting the cluster, and for whatever reason a resource cannot be found to be deleted, we should notify the user and proceed, instead of stopping altogether.

**Comment by JosephSalisbury** [comment]
I was having a think about how to raise issues to the user. I'd normally say Kubernetes events, but they're not really visible to the user for tprs. Thoughts?

**Comment by asymmetric** [comment]
Who is the user in this context? Is it the outer cluster admin? Or is it the customer?

**Comment by JosephSalisbury** [comment]
I think outer cluster admin. If we can work out how to surface this in monitoring or such, then we should be able to get it to the customer.

Metrics / events / logging?

**Comment by asymmetric** [comment]
This is partially done in master; we just need to make sure we are consistent.

**Comment by asymmetric** [comment]
Checked, we are consistent in continuing when resources cannot be deleted.
