### ISSUE TITLE
Agree on error handling practices

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#112]
At the moment, there are a couple of ways we do error handling:

* create an [error variable](https://github.com/giantswarm/aws-operator/blob/5e35c0e9d2095f12e2bbfb365ed5975cb0cf5403/resources/aws/errors.go#L17) with `errgo.New`, and run a [string comparison](https://github.com/giantswarm/aws-operator/blob/5e35c0e9d2095f12e2bbfb365ed5975cb0cf5403/resources/aws/subnet.go#L48) on the error message
* sometimes, we additionally define a [matching function](https://github.com/giantswarm/aws-operator/blob/5e35c0e9d2095f12e2bbfb365ed5975cb0cf5403/service/error.go#L12), which extracts the underlying error
* creating a [new type](https://github.com/giantswarm/aws-operator/blob/5e35c0e9d2095f12e2bbfb365ed5975cb0cf5403/resources/aws/errors.go#L24) for an error, and using [type assertions](https://github.com/giantswarm/aws-operator/blob/5e35c0e9d2095f12e2bbfb365ed5975cb0cf5403/service/create/loadbalancer.go#L123) on it

In cases where it's possible, I would argue it's better to use type assertions on the unwrapped error, since we all know, string comparisons are sad.

The error variable approach would be OK if we could then just do `if err == subnetFindError`, but this is not possible since we wrap errors over and over (to get the whole stack). Therefore we have to resort to string comparisons, or to creating the matching function (see case 2).

Incidentally, I think switching to `juju/errors` (cfr. https://github.com/giantswarm/microkit/issues/62) could alleviate our need for wrapping all the way up, thanks to the [`ErrorStack`](https://github.com/juju/errors/blob/6f54ff6318409d31ff16261533ce2c8381a4fd5d/functions.go#L262) function.

WDYT?

**Comment by xh3b4sd** [comment]
- I think we should not use string comparison. 
- I think we should use error matcher functions since this is the go idiomatic way of handling errors. 
- I am not sure if dropping the error wrapping is a good thing. When we not do it we can easily log the stack where ever we need to in the code, but this becomes unhandy when debugging code in failure situations. Right now you can simply `fmt.Printf("%#v\n", err)` to see the whole thing. If we drop the wrapping convention we would need to `import` and maybe `go get` the lib of the stack function whenever something breaks. This would increase the development/debug workflow. I see this becoming annoying quite quickly.

**Comment by asymmetric** [comment]
I proposed unwrapping the error at the top-most level, i.e. where we need to actually decide on what to do based on its type. In other situations, nothing would change and we would keep the wrapping as it is.

As to matcher functions being idiomatic for errors, could you please point to a couple of places that demonstrate that? I learned the error type approach from [this blog post](https://blog.golang.org/error-handling-and-go), which automatically makes this approach idiomatic as well (since it's on the offical Go site) :). The other upside of error types is that fields can be added to the struct and used in the error message.

In the end though, I'm absolutely fine with both of these last 2 solutions, as long as we don't do string comparison anymore :).

**Comment by xh3b4sd** [comment]
The os package has several error matchers. 

- https://golang.org/pkg/os/#IsExist
- https://golang.org/pkg/os/#IsNotExist
- https://golang.org/pkg/os/#IsPermission

**Comment by asymmetric** [comment]
OK, let's go with matcher functions then! :tada:

**Comment by asymmetric** [comment]
We agreed that:

* Errors are private.
* Each error has its matcher.
* Matchers are public.
* Error messages start lower case.
* Errors and matchers are grouped together.
