### ISSUE TITLE
Open necessary ports in Security Group

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#119]
Currently, the SG only allows traffic on TCP port 22.

We need to at least allow incoming connections on the API Server ports.

Also, cfr. #118.

**Comment by rossf7** [comment]
Found a related bug which is the security group is opening ports 0-22 rather than just port 22. Run out of time today but I'll fix this and the API server ports in the morning.

**Comment by asymmetric** [comment]
@rossf7 can this be closed?

**Comment by rossf7** [comment]
@asymmetric I've moved to PDV. I'd like to keep open till we've done an end to end test.

I also need to check the ports in kubernetesd as its still using 6443 when creating the TPO.

**Comment by rossf7** [comment]
I checked ports during AWS testing and they are correct.
