### ISSUE TITLE
Time out waiting for secrets even though they exist

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/aws-operator#142]
Towards https://github.com/giantswarm/giantswarm/issues/1388

Had multiple scenarios where the operator is waiting for secrets that have already been created, though it is intermittent.

My gut feeling is that https://github.com/giantswarm/aws-operator/blob/7de640076e360c6e6bc066d5954779b5247620c9/service/create/secrets.go#L34 watches for new secrets, so the system works if the secrets are created _after_ the watch is setup, but it doesn't work if they're setup _before_ - there's a race

**Comment by JosephSalisbury** [comment]
Looks like etcd certs aren't being generated due to the new 127.0.0.1 alt name

**Comment by JosephSalisbury** [comment]
```
{"caller":"github.com/giantswarm/cert-operator/service/crt/service.go:149","error":"could not issue cert '[{/go/src/github.com/giantswarm/cert-operator/service/crt/cert_signer.go:34: } {/go/src/github.com/giantswarm/cert-operator/vendor/github.com/giantswarm/certctl/service/cert-signer/cert_signer.go:70: } {Error making API request.\n\nURL: PUT https://vault.eu-west-1.aws.private.giantswarm.io/v1/pki-k2u3o/issue/role-k2u3o\nCode: 400. Errors:\n\n* name 127.0.0.1 not allowed by this role}]'","time":"17-04-21 16:46:22.238"}
```
```
17:46:10 ~/go/src/github.com/giantswarm/gsctl (cluster-clusters)
$ kubectl get certificate
NAME           KIND
k2u3o-api      Certificate.v1.giantswarm.io
k2u3o-calico   Certificate.v1.giantswarm.io
k2u3o-etcd     Certificate.v1.giantswarm.io
k2u3o-worker   Certificate.v1.giantswarm.io
17:46:54 ~/go/src/github.com/giantswarm/gsctl (cluster-clusters)
$ kubectl get secret
NAME                  TYPE                                  DATA      AGE
default-token-0fc9x   kubernetes.io/service-account-token   3         21d
k2u3o-api             Opaque                                3         36s
k2u3o-calico          Opaque                                3         35s
k2u3o-worker          Opaque                                3         34s
```

still facing this

**Comment by rossf7** [comment]
The problem with issuing the etcd cert is because 127.0.0.1 is not in the allowed domains for the PKI backend. The PKI backend is being created by cluster-service so 127.0.0.1 needs to be added to the config map.

The cert-operator is not creating the PKI backend. It checks for an existing backend and finds the one created by cluster service. We want to split the CA logic out of cert-operator and remove the logic from cluster-service in giantswarm/cert-operator#27.

**Comment by rossf7** [comment]
The etcd cert is now being issued with an alt name of 127.0.0.1 now that https://github.com/giantswarm/cluster-service/pull/105 is deployed.

**Comment by JosephSalisbury** [comment]
This is good now
