### ISSUE TITLE
Place workers back in a private subnet

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#160]
To simplify the work on https://github.com/giantswarm/giantswarm/issues/1381, we have moved the workers to the same public subnet where the masters are.

This is because forwarding traffic from an ELB to a private subnet is non-trivial.

At some point, we want to move the workers back to their own private subnet.

**References**

* https://stackoverflow.com/questions/9257514/amazon-elb-in-vpc/9638048#9638048
* https://stackoverflow.com/questions/22541895/amazon-elb-for-ec2-instances-in-private-subnet-in-vpc/22542126#22542126

**Comment by xh3b4sd** [comment]
For my interest. Is this already done? I have in mind something happened here already.

**Comment by asymmetric** [comment]
Nope, it's not done. We are planning on figuring out the best way to do it as part of a "Networking redesign".

**Comment by xh3b4sd** [comment]
@puja108 is this related to https://github.com/giantswarm/giantswarm/issues/1803?

**Comment by puja108** [comment]
yes, linked in the issue

**Comment by xh3b4sd** [comment]
I guess this is done.
