### ISSUE TITLE
Intermittent errors when tagging resources

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#161]
Sometimes the operator breaks when tagging a resource, with an error like

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:345","error":"could not create route table: [{/home/asymmetric/code/go/src/github.com/giantswarm/aws-operator/resources/aws/route_table.go:66: } {/home/asymmetric/code/go/src/github.com/giantswarm/aws-operator/resources/aws/route_table.go:89: } {InvalidRouteTableID.NotFound: The routeTable ID 'rtb-23325f44' does not exist\n\tstatus code: 400, request id: c674e40f-209b-49dc-866c-53f736664c4a}]","time":"17-04-26 12:48:22.951"}
```

I believe this is because of a race. At the moment of sending the tagging request, the resource hasn't been fully created yet.

We should wait until the resource has been effectively created (using one of the `WaitUntil` methods) before tagging.

**Comment by asymmetric** [comment]
Got this again, specifically [here](https://github.com/giantswarm/aws-operator/blob/419dce99b4415f20eecaeb270e7195d2178b1045/resources/aws/route_table.go#L80).

There is no `WaitUntilRouteTableAvailable` function in the SDK, so I think we'll have to work around it wit [`DescribeRouteTables`](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeRouteTables).

**Comment by kopiczko** [comment]
Closing it's in later. Please reopen and put in inbox if relevant.
