### ISSUE TITLE
Specify ELB name in TPO?

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#165]
Currently, the ELB name is inferred by parsing the `Domain` field of the TPO, and taking the first subdomain.

e.g. [this](https://github.com/giantswarm/aws-operator/blob/0f849addad1345c53084c8d6074480a23ade06eb/examples/cluster.yml#L17) will generate an ELB with name "etcd".

Do we instead want to have the ELB name explicitly defined in the TPO?

**Comment by xh3b4sd** [comment]
Note that I put the issue into the inbox of the operator board. When you only select the board here, it is awaiting triage.

**Comment by xh3b4sd** [comment]
We discussed in operator board sync that we are good enough right now with generating the ELB name. Cooool.
