### ISSUE TITLE
Handle situations where AWS API return many resources, despite the fact of uniqueness

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/aws-operator#170]

**Comment by asymmetric** [comment]
Can you provide some context for this one?

**Comment by nhlfr** [comment]
The context is that currently we are checking whether list of resources is non-empty and we are just getting the first element if the list contains any amount of elements:

https://github.com/giantswarm/aws-operator/blob/master/resources/aws/vpc.go#L33-L37

This issue is about raising an error when we have more than one result. Also, I would like to reduce copying&pasting the code with checking for list lenghts in resources.
