### ISSUE TITLE
No communication when stuck in `backoff.Retry`

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#174]
When the operator gets stuck in a Retry loop, all the user sees is a frozen application, with no visibility into what is causing the operation to fail.

This is because we don't perform logging from `resource`s.

We could add a `Logger` to the aws resources like `ELB`.

**Comment by xh3b4sd** [comment]
I think it would be super cool if we would register a retry handler and emit metrics about retries and do some logging.

**Comment by nhlfr** [comment]
I need to address https://github.com/giantswarm/aws-operator/pull/251#discussion_r117026604
