### ISSUE TITLE
Use a separate ELB for etcd and not the master ELB

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#176]
Towards giantswarm/giantswarm#1388

We've added etcd to the master ELB but the health check defaults to the first port which is 443. This won't work because etcd needs to be available first.

Adding a health check for etcd on port 2379 will work but we should think about having a separate ELB for etcd.

**Comment by asymmetric** [comment]
Creating another ELB is not much work. If that's the correct choice, we should do it.

**Comment by rossf7** [comment]
@asymmetric I agree having a separate ELB for etcd with its own health check is better. 

From looking at configuring the health check its about the same amount of work and a worse design. I'll switch to implementing a separate ELB.
