### ISSUE TITLE
Fix Hosted Zone parsing

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#177]
Towards giantswarm/giantswarm#1388

[`hostedZoneName`](https://github.com/giantswarm/aws-operator/blob/master/service/create/domains.go#L103) expects domains to look like `api.customer.aws.giantswarm.io`.

This expectation is wrong.

Domains in TPOs created by kubernetesd actually look like `etcd.pbmva.g8s.eu-west-1.adidas.aws.giantswarm.io`.

**Comment by rossf7** [comment]
Due to this bug we're currently creating a HZ per cluster which is incorrect.  

After discussing with @calvix for `etcd.pbmva.g8s.eu-west-1.adidas.aws.giantswarm.io` the hosted zone should be `g8s.eu-west-1.adidas.aws.giantswarm.io`. There is a 10k limit on DNS records so doing this per installation and per region is better than using `aws.giantswarm.io`.

**Comment by calvix** [comment]
Yes, as we had the discussion in slack. Create host-zone manually and then just create A DNS records like 
`etcd.pbmva` in HZ `g8s.eu-west-1.adidas.aws.giantswarm.io`

**Comment by asymmetric** [comment]
Why should we create the HZ manually?

**Comment by rossf7** [comment]
There's a manual step to delegate the HZ subdomain from the primary DNS. But I think we can keep the logic to create the HZ the first time it sees a new subdomain.

Since there's the manual step I think we need to add the HZ subdomains to awstpr rather than parsing them from the domain names. This also prevents the problem we had with different domain name structures.

**Comment by asymmetric** [comment]
I'm not sure. The manual step is only necessary in this particular setup, where we handle DNS for the main domain at one provider, and then delegate to Route53. So it's not a general requirement.

I kind of feel that the HZ is an implementation detail rather than a parameter I would like to be concerned with at a high-level, but OTOH you are right that having it in the TPO allows for more flexibility.

In the end it's a matter of UX though, and it's up to you to decide what you prefer.

**Comment by rossf7** [comment]
Yes its a tricky one. I think in some installations we may need to delegate DNS but not in all. So its hard to know if its a general requirement. I also see the problem with adding too much implementation config into the TPO.

If we remove the `api.pbmva` prefix then the HZ name is correct. The rest of the domain name comes from a flag in the architect installation config. So that's a more flexible solution and I'll have a go at implementing that.

See https://github.com/giantswarm/architect/blob/master/installation/aws.go#L78

**Comment by rossf7** [comment]
So removing the first 2 subdomain is what the code is already doing ;) We need to delegate `g8s.eu-west-1.adidas.aws.giantswarm.io` and `g8s.eu-west-1.adidas.aws.gigantic.io` in CloudFlare for this to work.

**Comment by asymmetric** [comment]
See https://github.com/kinvolk/aws-operator/commit/a53aa997c867f8c37fecf66864bd503caaa67b70

**Comment by calvix** [comment]
zones delegated

**Comment by rossf7** [comment]
Now that the correct subdomain is delegated etcd domain name resolves externally and within the cluster.
