### ISSUE TITLE
Write a tool for generating the test certificates

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/aws-operator#18]
[This](https://paste.fedoraproject.org/paste/e~7vy6KHKNRWwgnKRFN7MV5M1UNdIGYhyRLivL9gydE=) may be a good start, but needs to be polished, or maybe written in Go.

Requirement for the tool - we need to have the following tree of SSL certificates (passwordless, 512 or 1024 bit).

certs/
├── apiserver-ca.pem
├── apiserver-key.pem
├── apiserver.pem
├── calico
│   ├── client-ca.pem
│   ├── client-key.pem
│   └── client.pem
├── etcd
│   ├── server-ca.pem
│   ├── server-key.pem
│   └── server.pem
├── worker-ca.pem
├── worker-key.pem
└── worker.pem

**Comment by xh3b4sd** [comment]
FYI check https://github.com/giantswarm/certctl and https://github.com/giantswarm/giantswarm/wiki/certificate-generation-%23ssl-%23tls-%23certificates. That should help you.

**Comment by iaguis** [comment]
> FYI check https://github.com/giantswarm/certctl and https://github.com/giantswarm/giantswarm/wiki/certificate-generation-%23ssl-%23tls-%23certificates. That should help you.

AFAIU the scope of this issue is just to create as simple tool for providing test certificates to the operator so we can have a cluster running so using certctl seems overkill.

In the end, the future [Certificate/Vault Operator](https://github.com/giantswarm/giantswarm/issues/1255) will pass the certs to the aws-operator and we won't need this tool anymore.

Does that make sense?

**Comment by xh3b4sd** [comment]
Certctl just creates certificates for you. So you can write your own script or you can just use the tool that is already there. I only thought it would help you. If you think it does not, go for what works best for you.

**Comment by xh3b4sd** [comment]
And yes, we want to use the Vault/certificate operator in the end and not use certctl inside of the cluster automation at all.

**Comment by iaguis** [comment]
> Certctl just creates certificates for you.

If it's as simple as that we should use it. I thought it required a somewhat complicated vault setup (I never used vault).

**Comment by xh3b4sd** [comment]
You maybe want to read the wiki first. The PKI setup is also done by certctl via `certctl setup`. Then you can issue certificates with `certctl issue`.

**Comment by nhlfr** [comment]
@xh3b4sd certctl is a private project... Dunno whether we can talk about it here at all. :)

**Comment by xh3b4sd** [comment]
We did this.
