### ISSUE TITLE
Security Group rules block too much traffic

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#227]
Even if we allow a security group as source, the traffic still gets blocked.

This is because we are connecting to the instances through the public internet, and Security Groups only work within the VPC, so only with private IP addresses and DNS records.

/cc @rossf7 @calvix @puja108

**Comment by rossf7** [comment]
We're going to defer restricting access to etcd until later. @asymmetric can you revert the private hosted zone changes and also make etcd accessible on `0.0.0.0/0`.

**Comment by calvix** [comment]
I am pretty sure you can configure Security groups for public networks(and allow public connections), I will try have a look later.

**Comment by asymmetric** [comment]
Closed in #233.
