### ISSUE TITLE
Cloudinit deprecated

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#235]
As announced in the README, [cloudinit](https://github.com/coreos/coreos-cloudinit) has been deprecated.

We should switch to [Ignition](https://github.com/coreos/ignition), or evaluate other options.

**Comment by iaguis** [comment]
Some discussion about this in kube-aws: https://github.com/kubernetes-incubator/kube-aws/issues/252#issuecomment-272991248

**Comment by nhlfr** [comment]
Dup of #156
