### ISSUE TITLE
Remove oneshot unit that sets BRIDGE_IP

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#241]
The BRIDGE_IP hack was removed from calico in https://github.com/giantswarm/k8scloudconfig/pull/111

If we don't need it we can also remove the oneshot unit hack that sets it on AWS.

See https://github.com/giantswarm/aws-operator/blob/master/service/create/templates.go#L73

**Comment by asymmetric** [comment]
Do we even read that `calico-environment` file at some point? It seems the calico unit only uses `network-environment`. Is it read implicitly?

**Comment by asymmetric** [comment]
[Yes](https://github.com/giantswarm/k8scloudconfig/blob/f6e35c3c7b2f87fe4ea37f828db64acb79ee5860/templates.go#L602).

**Comment by rossf7** [comment]
OK that should have got removed when BRIDGE_IP was removed ;) We should do it as part of this cleanup.
