### ISSUE TITLE
Infer full region name from AZ + letter

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#243]
Right now, the region name in the TPO is `eu-central-1a`, i.e. it repeats the AZ.

This is the format that AWS uses, but the downside is that we have forgotten multiple times to update the region when we updated the AZ.

So we should infer the full region name from the AZ + the region letter within the operator.

See #242.

**Comment by kopiczko** [comment]
@puja108 closing it's in later. Please reopen and put in inbox if relevant. BTW since this is the AWS format  it can be confusing.
