### ISSUE TITLE
Use auto scaling groups on AWS

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#258]
Currently we launch EC2 instances individually via the API. We should move to auto scaling groups for self healing and rolling updates.

**Comment by rossf7** [comment]
We may also need multiple ASGs with different node labels. This is so specialist workloads can be run on them. cc @puja108

**Comment by puja108** [comment]
Here's a nice example how to let AWS handle the k8s draining (with a lifecycle hook) when scaling down: https://blog.powerupcloud.com/scale-down-a-kube-cluster-minion-without-downtime-using-aws-autoscaling-lifecycle-hook-part-iii-374387d94107

**Comment by rossf7** [comment]
@nhlfr discussed ASG's with @puja108 and I'm afraid we need to change direction. We're not sure on using SSM Agent as we also need a way of draining nodes on KVM.

But replacing the runMachines for workers with an ASG would help a lot. As then worker nodes will be replaced and later we can update the desired capacity to scale workers. Please could you prioritise that change. Let me know if you have questions.

**Comment by rossf7** [comment]
## Operator Resources

- [ ] Launch Configuration
- [ ] Auto Scaling Group

## Service

- [ ] Create launch config
- [ ] Create auto scaling group
- [ ] Delete auto scaling group
- [ ] Delete launch config

**Comment by asymmetric** [comment]
When discussing this with @rossf7, we were wondering whether it makes sense to have an ASG with size 1 for the master too.

The upside is that we wouldn't have to maintain 2 different instance initialization flows (`runInstances` and the ASG).

We will see which approach makes things easier, i.e. no final decision yet.

**Comment by rossf7** [comment]
Another thing to mention is when creating the worker ASG we can include the ingress ELB. This will then handle registering and deregistering instances with the ELB automatically. I like this approach and we've already created the Ingress ELB.

However in architecture review we also talked about self hosting the ELBs. So we could create an Ingress service in k8s of type load balancer. Again no final decision has been made yet.

**Comment by rossf7** [comment]
We want the ability to terminate specific worker nodes. This is possible with ASGs by detaching the instance and setting the should decrement desired capacity flag to true. Once the instance is detached we need to terminate it using the EC2 API.

See https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#example_AutoScaling_DetachInstances

**Comment by puja108** [comment]
btw, we should maybe also have a look at https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md to see if we could be compatible with the standard autoscaler somehow.

**Comment by puja108** [comment]
@teemow mentioned that we should be careful with ASG for master, as "healing" the master would kill etcd.

**Comment by asymmetric** [comment]
@puja108 @teemow when exactly could healthy machines be killed? Is that an actual risk or just precaution?

**Comment by puja108** [comment]
whenever healthcheck fails AFAIK, if we can ensure that etcd comes back with the same storage that should work, but not sure how ASGs work

**Comment by asymmetric** [comment]
A few open questions:

* What should the max amount of workers be?
* Should it be specified in the TPO?
* When do we want to trigger the scaling out?
* Or do we want to do manual scaling at the beginning?

**Comment by rossf7** [comment]
@puja108 we can provision EBS storage in the ASG config but so far none of the EC2 instances we launch have storage provisioned.

@asymmetric for the first version we want to set the desired capacity to the number of nodes in the TPO. This gives us some "self healing" as failed worker nodes will be replaced. Scaling the number of workers will come later. It also needs changes to the API and update watch support in the operator.

For the auto scaler I'd say we should try and make our changes compatible with it but it will also come later.

For whether we use an ASG for the master there is a trade off. Using an ASG means we only have 1 way of launching instances. But if we replace a broken worker node with no state that's probably worse than the master just dying. So this needs more discussion.

**Comment by puja108** [comment]
Yes, manual scaling for now, and then we can build a GS autoscaler that works with any GS setup (not only AWS).

Btw, we don't need to be able to run the official auto-scaler cause it would interfere with our operators anyway. Just could help thinking about multi-ASG and things like naming, structuring maybe I thought.

@rossf7 for now we won't provision EBS from the get go. I'd like to move more in direction of having dynamic EBS provisioner in the clusters so they can just provision EBS as PVs on the fly. Then K8s would also handle reattaching EBS on reschedulings and stuff AFAIK. Not sure if that needs to be somehow "supported" in the ASG/EC2 configs, but that's part if a different story.
