### ISSUE TITLE
Split aws-operator into micro operators

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#259]
A micro operator approach is the architecture we are aiming for. Splitting aws-operator into smaller operators should make it easier to work on changes in parallel.

**Comment by xh3b4sd** [comment]
Is this issue still valid? Do we have concrete suggestions here? There was once the idea of having operators for CRUD operations but now I do not think this would be better.

**Comment by rossf7** [comment]
Closing. I think we should make the operator smaller by replacing Go SDK with Cloud Formation templates.
