### ISSUE TITLE
Fix decoding errors

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#265]
The operator, while functional, prints out a lot of errors like

```
E0523 09:46:41.130525       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Aws" is registered for version "cluster.giantswarm.io/v1"
```

See https://github.com/kubernetes/client-go/issues/8 for more info.

**Comment by asymmetric** [comment]
Applying the ugoji workarounds on the vendored `awstpr` didn't fix the issue: https://github.com/giantswarm/aws-operator/compare/asymmetric/test-awstpr-ugoji

**Comment by asymmetric** [comment]
@puja108 any idea what that error might mean? This is not high priority though.

**Comment by xh3b4sd** [comment]
AFAIK this is done. Operatorkit sorted this out.

**Comment by xh3b4sd** [comment]
We saw this again.

**Comment by rossf7** [comment]
I've checked the AWS installs and there aren't any decoding errors. So I'm going to close this again.

Ping @xh3b4sd FYI
