### ISSUE TITLE
aws-operator doesn't wait for TPR to be initialised

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/aws-operator#266]
```
Failed to list *awstpr.CustomObject: the server could not find the requested resource
```

Similar to cert-operator. operaotrkit/tpr will help here.

**Comment by asymmetric** [comment]
I wonder if TPR creation is an asynchronous process, because in the code, we first create the TPR and then start the Informer.

**Comment by kopiczko** [comment]
Yes it is, see https://github.com/giantswarm/cert-operator/pull/53/commits/e0026606a0c76140dbd35fc16b362cba760ae8d0

**Comment by rossf7** [comment]
Closing, `operatorkit` does this for us. ❤️
