### ISSUE TITLE
"wait for domain" unit not needed for kvm-operator

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/aws-operator#278]
@calvix mentioned that the unit waiting for domains not be necessary for KVM. So it should be moved out of k8scloudconfig. 

See https://gigantic.slack.com/archives/C2MS2VB37/p1495642677952008.

**Comment by calvix** [comment]
we need it on aws but not on KVM, so the question is if we can easily remove it from KVM setup

**Comment by xh3b4sd** [comment]
Even though it might not be needed it is there and does not hurt. Should we just move on with our lives?

**Comment by calvix** [comment]
yeah, I think we can live with that, if the DNS records do not exist in kvm, the cluster would not work anyway
