### ISSUE TITLE
Use separate security group for the API ELB

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/aws-operator#318]
Currently the API ELB is in the masters security group. Moving it to a separate security group means only the API ELB needs to be `0.0.0.0/0`

This is part of the security changes but can be implemented before we restrict the port access.

**Comment by xh3b4sd** [comment]
@rossf7 can you shed some light on this? Is this still valid?

**Comment by rossf7** [comment]
Yes, I think we still need this. This means only the API ELB needs to be `0.0.0.0/0` and we restrict the master node to connections from the ELB and workers sec groups.

Ping @teemow is this part of guest cluster lockdown?

**Comment by teemow** [comment]
yes this is part of https://github.com/giantswarm/giantswarm/issues/1803

**Comment by xh3b4sd** [comment]
Then lets close this one here.
