### ISSUE TITLE
Make EBS parameters configurable

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#320]
The EBS volume size, type and mount point are [hard-coded](https://github.com/giantswarm/aws-operator/blob/2e7bd95f6541976b64ce4627aec8d214771619a0/resources/aws/launch_configuration.go).

We should make them configurable, either as variables in the TPO, or as flags to the operator.

/cc @rossf7

**Comment by rossf7** [comment]
@asymmetric I thought more on this and I think you're right. We should add this config to the TPO.

My worry was about the TPO getting too big. But storage is an important property of the cluster so ignore me on that ;)

**Comment by xh3b4sd** [comment]
Can somebody give an update on this issue? Is this still relevant? Is this maybe already covered by something else? Is this maybe even done already?

**Comment by rossf7** [comment]
Ack. I think it can be closed. I'll reply after the sync.

**Comment by rossf7** [comment]
For me this is only useful if we also make it configurable in the frontend / API. Doing that end to end is non-trivial and I haven't seen a demand from customers.

We can reopen if it gets priority.

cc @puja108
