### ISSUE TITLE
Can we make the MachineDeploymentLaunchTemplateOverrides Configurable?

### ISSUE THREAD

**Issue by johannges** [giantswarm/aws-operator#3221]
It would be nice to be able to provide a custom MachineDeploymentLaunchTemplateOverrides list, so the user can use Spot Instances of all m5(a/d/ad/nz/..) m4(a/d/...) and could faster adopt new Instance familys like m6i, to reduce price and improve performance, while at the same time improving spot stability.

**Comment by pipo02mix** [comment]
I have been talking to Johannes about it and ideally we add the latest m5/m6x instances to the pool

**Comment by alex-dabija** [comment]
I created a roadmap issue to add additional AWS x86_64 instance types: https://github.com/giantswarm/roadmap/issues/672 .

**Comment by alex-dabija** [comment]
The requested instance types are now available for use. More information is available in our [roadmap issue](https://github.com/giantswarm/roadmap/issues/672).
