### ISSUE TITLE
Create operator kit for common operations?

### ISSUE THREAD

**Issue by jamiehannaford** [giantswarm/aws-operator#325]
I'm wondering whether there is enough overlap in different operators to warrant some kind of common library that will make the lives of those who want to write an operator easier. Have you folks thought about doing this?

I've already reached out to [CoreOS's etcd-operator](https://github.com/coreos/etcd-operator/issues/1125) and [rook](https://github.com/rook/rook/issues/740) about this, and started to write proposal for an OperatorKit here:

https://docs.google.com/document/d/1NJhFcNezJyLM952eaYVcdfIQFQYWsAx4oTaA82-Frdk

Is this something that would benefit the wider operator community? If so, would love to hear your feedback in that proposal.

**Comment by jamiehannaford** [comment]
@rossf7 @JosephSalisbury @nhlfr @asymmetric Is this something you folks are interested in?

**Comment by rossf7** [comment]
@jamiehannaford Yes, we're interested and we've started creating a library as we need it for our operators :) https://github.com/giantswarm/operatorkit

But we see it being useful to the wider operator community. The proposal looks interesting and there is some crossover with what we already have. I'll have a proper look and add feedback when I get a chance.

**Comment by puja108** [comment]
@jamiehannaford great to see even more interest in this topic, let's see if we can somehow put our efforts together and get this thing out for the wider community to use.

**Comment by jamiehannaford** [comment]
Closing as we now have a requirements doc and community interest. Next steps will be [proposing](https://docs.google.com/document/d/1ChcMp6pnEK13sSwfThKb5UPBYdrJ-3z4qIsnMMoNEKs) it as an incubator project.
