### ISSUE TITLE
add health check if the operator has access to the AWS account

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/aws-operator#381]

**Comment by xh3b4sd** [comment]
We think there is already something like this. It would be good to move this then to https://github.com/giantswarm/microendpoint/ to have the unified jazz.

**Comment by kopiczko** [comment]
I'm afraid microendpoint has potential to become dependency hell. See https://github.com/giantswarm/microendpoint/issues/11

**Comment by xh3b4sd** [comment]
IMO this is done.
