### ISSUE TITLE
VPC peering errors processing existing clusters

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#397]
There are errors appearing when the operator reprocesses existing clusters. This is because these TPOs don't have the necessary settings for VPC peering. These errors do not affect creating new clusters.

We should either not create the VPC peering or update the existing TPOs.

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:488","error":"error processing cluster 'y22nx': '[{/go/src/github.com/giantswarm/aws-operator/service/create/service.go:659: could not create vpc peering connection: '[{/go/src/github.com/giantswarm/aws-operator/resources/aws/peering.go:80: } {/go/src/github.com/giantswarm/aws-operator/resources/aws/peering.go:103: } {MissingParameter: The request must contain the parameter peerVpcId\n\tstatus code: 400, request id: 346710a0-c9ab-430d-a708-c0764a7e93e5}]'} {execution failed}]'","time":"17-09-06 10:29:45.400"}
```

**Comment by xh3b4sd** [comment]
Did we see this again? Does somebody know more? /cc @JosephSalisbury @puja108

**Comment by JosephSalisbury** [comment]
I'd need to check

**Comment by xh3b4sd** [comment]
Lets try again. Is this issue still valid? Can we close it? Is there still a real problem?

**Comment by rossf7** [comment]
This is because of old clusters that don't have the VPC peering settings. I'd say it's the same as #466 and we should close.
