### ISSUE TITLE
remove Makefiles with glide-cc

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#407]
We were using a Makefile to update vendor that uses glide-cc to delete unused code. This deletes ~2.6 million lines of code so there is some benefit.

But it's not standard across our projects and its very easy to forget to run `make update-vendor`. We should decide if we want to keep using glide-cc or delete the Makefile.

**Comment by xh3b4sd** [comment]
My personal opinion. I do not see the value in this. We also want to move away from glide ASAP (whenever this "soon" will be).

**Comment by rossf7** [comment]
I think we should remove it. It does remove a sizeable amount of code. But only using it in a few repos is confusing and it's too easy to forget and the extra code ends up in a PR.

**Comment by xh3b4sd** [comment]
Sounds like the decision was made. Moving to backlog. <3
