### ISSUE TITLE
Host cluster CIDR block can be nil when creating security group rules

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#451]
In local testing the host cluster CIDR block can be nil which causes a panic. For now an error is returned if this occurs. Retry logic for the VPC peering connection may be needed to fix this.

**Comment by xh3b4sd** [comment]
Is this issue still valid? Is it solved or will it be solved by the use of cloudformation?

**Comment by rossf7** [comment]
Closing. I've only seen this locally and will be fixed by cloud formation.

**Comment by JosephSalisbury** [comment]
Raising to postmortem. Vodafone hit this hard.

**Comment by teemow** [comment]
@corest please take this to your team.

**Comment by corest** [comment]
@rossf7 FYI

**Comment by rossf7** [comment]
Fix is merged. We now retry getting the VPC peering connection if the accepter and requester CIDRs are not yet populated.

After the max backoff if the data is not present the current execution of the operator will fail. But this is the same as the previous error check which failed without a retry.
