### ISSUE TITLE
Idle timeout for etcd should be at least 1 hour

### ISSUE THREAD

**Issue by r7vme** [giantswarm/aws-operator#454]
Many services "watch" etcd, so it's expected that connections to etcd will not be dropped after 60sec (current elb idle timeout).

I see two solutions:
1) increase idle timeout to 1 hour
2) switch from ELB to DNS cname which directly point to master node

This timeout issue probably is the root cause of Calico/Confd issue, when new nodes can not join Calico, becuase existing nodes missed events from etcd. https://github.com/giantswarm/giantswarm/issues/1687#issuecomment-328551514

That happens in customer guest clusters periodically.

cc: @teemow @puja108 @rossf7

**Comment by calvix** [comment]
2. is not possible atm (we discussed this on sig-updates) so let's do start with 1, should be super simple hack

**Comment by puja108** [comment]
there's some PRs by Tim from IC consult that will make these timeouts configurable through the TPR:
https://github.com/giantswarm/awstpr/pull/45/files

**Comment by rossf7** [comment]
Yes the change from Tim @ IC Consult is to use the same timeout for all 3 ELBs. If there is no need to have separate values then I think we can go with that.

**Comment by puja108** [comment]
Oh, I thought this is separate values, I would vote for separate values as I'm not so sure we want to just increase to maximum (60 min) for all ELBs.

**Comment by rossf7** [comment]
The `awstpr` does have separate timeouts. Ignore me on this!

**Comment by rossf7** [comment]
Idle timeout set to 3600 secs in #445
