### ISSUE TITLE
S3 bucket isn't created automatically

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/aws-operator#53]
Which causes the following error:

```
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:177","info":"successfully created third-party resource","time":"17-03-15 15:43:40.237"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:274","info":"starting watch","time":"17-03-15 15:43:40.237"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:186","info":"creating cluster 'test-michal'","time":"17-03-15 15:43:40.238"}
{"caller":"github.com/giantswarm/aws-operator/service/create/keypair.go:51","info":"keypair 'test-michal' exists, reusing","time":"17-03-15 15:43:40.452"}
{"caller":"github.com/giantswarm/aws-operator/service/create/policy.go:68","info":"role 'example-cluster-EC2-K8S-Role' exists, reusing","time":"17-03-15 15:43:41.911"}
{"caller":"github.com/giantswarm/aws-operator/service/create/policy.go:93","info":"instance profile 'example-cluster-EC2-K8S-Role' exists, reusing","time":"17-03-15 15:43:42.627"}
{"caller":"github.com/giantswarm/aws-operator/service/create/service.go:243","error":"NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: D98777358A8C255F","time":"17-03-15 15:43:43.398"}
```

**Comment by xh3b4sd** [comment]
FYI I added the issue to the operator board for you.

**Comment by iaguis** [comment]
My idea with this is that we use a single bucket for all the clusters. The way the policy is set up, every cluster will see only its own subdirectory in the bucket.

If we use a single bucket for all the clusters I think it can be created beforehand and we shouldn't bother with creating it in the operator.

We could create per-cluster buckets and provide a pre- or suffix and then it will make sense that we create it in the operator.

I don't have strong feelings on this. Does anybody has opinions on it?

**Comment by xh3b4sd** [comment]
The operator should take care about everything that is necessary to actually use the operator. It should only take a few Kubernetes manifests to create and the rest happens. From a user point of view it would be really odd to do x different manual steps to satisfy the operators requirements. 

I think the separation of sub dirs within the S3 buckets is cool. It should not be possible by accident to make users aware about internals of clusters that do not belong to them.

**Comment by iaguis** [comment]
> The operator should take care about everything that is necessary to actually use the operator. It should only take a few Kubernetes manifests to create and the rest happens.

Good point. Should we then try to generate a bucket name instead of the operator taking it as a CLI argument?

**Comment by xh3b4sd** [comment]
I think both. Lets use a decent default value/algorithm and let the user decide to overwrite it.
