### ISSUE TITLE
Consume certificates from k8s secrets

### ISSUE THREAD

**Issue by iaguis** [giantswarm/aws-operator#61]
Getting them via the filesystem was a temporary implementation. In the future, the certificate operator will generate the certs and put them into kubernetes secrets which will get consumed by the aws-operator.

We should implement this in the aws-operator.

**Comment by asymmetric** [comment]
Done in https://github.com/giantswarm/aws-operator/pull/86

**Comment by asymmetric** [comment]
Needs to be properly tested with secrets created by actual certificate operator though, reopening.
