### ISSUE TITLE
upgrade aws-operator vendor deps to latest master

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/aws-operator#640]
In order to move forward on host clusters we have to get back on track to master with the vendor deps like in other operators. We can then also move to use `dep` instead of `glide`. How to coordinate that? Does somebody want to take it? I want to have this done this week. I can also do it but do not want to rain on anybodies parade. Let me know what you think. 

/cc @rossf7 @fgimenez @JosephSalisbury @kopiczko @jgsqware

**Comment by kopiczko** [comment]
That would be great.

Just small comment for me. To make life a little bit easier you can use legacy branch of certs: https://github.com/giantswarm/certs/pull/3

That way interface stays the same. And it can be updated later. This is the only reason I still keep this PR open.

**Comment by rossf7** [comment]
I can take this as my next task. Having aws-operator on such old deps is a problem and I don't want to block the host cluster upgrades.

Thanks for the tip on the legacy branch for certs. I'll shout if I get stuck.

**Comment by xh3b4sd** [comment]
Awesome Ross. Thanks a lot. <3

**Comment by xh3b4sd** [comment]
This is done. Thanks to anybody involved.
