### ISSUE TITLE
Change etcd data location

### ISSUE THREAD

**Issue by rossf7** [giantswarm/aws-operator#651]
We store Etcd data in `/etc/kubernetes/data/etcd` which is non standard. As suggested by @teemow we should use `/var/lib/etcd`

CC @fgimenez

**Comment by fgimenez** [comment]
Makes total sense, we will need also to change the setup (https://github.com/giantswarm/k8scloudconfig/blob/master/v_3_0_0/master_template.go#L1696:10) and service (https://github.com/giantswarm/k8scloudconfig/blob/master/v_3_0_0/master_template.go#L1747) units in k8scc.

**Comment by fgimenez** [comment]
We also need to change at least azure-operator https://github.com/giantswarm/azure-operator/blob/master/service/cloudconfig/template.go#L633. Will propose the 3 PRs (k8scc, aws-operator and azure-operator) later, and do some testing on aws-operator, if things go good we could include the change in this release, WDYT @rossf7?

**Comment by rossf7** [comment]
It would be good to have this for the new clusters. If we're OK on time lets do it. Otherwise. I think it could wait till the next `k8scloudconfig` version.

**Comment by fgimenez** [comment]
aws-operator done, azure-operator changes ready https://github.com/giantswarm/azure-operator/pull/125 waiting for https://github.com/giantswarm/azure-operator/pull/122.

**Comment by fgimenez** [comment]
Done azure too in https://github.com/giantswarm/azure-operator/pull/125
