### ISSUE TITLE
Remove Elastic IP, use ELB

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#69]
As discussed, using an Elastic IP to assign a static, public IP address to the master(s) is a temporary solution, with the main drawback being that there's [a limit](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) on how many EIPs can be generated in a VPC.

The better solution is to setup a load balancer.

**Comment by xh3b4sd** [comment]
Note that I added the issue to the operator board for you.
