### ISSUE TITLE
weird version bundle states

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/aws-operator#695]
Right now we have these version bundles. 

- `0.1.0`: deprecated
- `0.2.0`: deprecated and WIP (should throw an error (https://github.com/giantswarm/versionbundle/issues/25))
- `1.0.0`: active (should be deprecated)
- `2.0.0`: deprecated
- `2.0.1`: deprecated
- `2.0.2`: active

Keeping the upgrade workflow up we should never keep older versions being active in case we introduce new ones. Is there a specific reason to keep `1.0.0` active for customer use when we are already on `2.0.2`?

/cc @rossf7 @fgimenez

**Comment by rossf7** [comment]
Thanks for raising neither of these should be active. Fix is in #696.
