### ISSUE TITLE
Handle case where bucket name has already been taken

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/aws-operator#94]
Since bucket names are globally unique, it's possible that the name we come up with has already been taken by someone else.

Right now, the name depends on the customer ID, which means changing that might allow us to create the bucket, but we might want to come up with better solutions.

**Comment by rossf7** [comment]
I believe the globally unique name is because each S3 bucket gets a DNS entry for serving files over HTTP.

I'd prefer to see a longer prefix to reduce the chance of collisions. The other approach I've often seen used is to include a random section in the bucket name.

**Comment by asymmetric** [comment]
How should we handle this?

Is notifying the user of the clash (and stopping the creation of the cluster) enough?

**Comment by JosephSalisbury** [comment]
I'm not certain what we would do if there was a clash. If we were notified of a clash, what would have to do to get it going again?

**Comment by xh3b4sd** [comment]
The customer ID must be unique. This must be enforced and validated in several places. The AWS operator should, if it wants to play nicely, check if the bucket is free. If it is not, we seem to have a more serious issue up the stack. There should then be some alerting and the action being started by the operator should be stopped.

**Comment by asymmetric** [comment]
> The AWS operator should, if it wants to play nicely, check if the bucket is free. If it is not, we seem to have a more serious issue up the stack. There should then be some alerting and the action being started by the operator should be stopped.

This is exactly what's happening now. Do we want to have some more intelligent logic/failsafe/handling?

**Comment by xh3b4sd** [comment]
So when the bucket name is already taken the operator throws an error and stops creating the cluster? I think this is then fine. In general we should at best teardown/cleanup/reverse all actions that have been applied to far but that is then another story.

**Comment by asymmetric** [comment]
Yes, this is what [this logic](https://github.com/giantswarm/aws-operator/blob/1bd359f72cab634755854495f22a2b67e3795ed0/resources/aws/bucket.go#L21-L27) is supposed to do.

If the bucket name is taken by us, everything is good. Otherwise, we error out. This is handled up the stack as a hard error and we stop the creation of the cluster.

**Comment by xh3b4sd** [comment]
So this issue is sorted now?

**Comment by asymmetric** [comment]
I believe so.
