### ISSUE TITLE
Make security group rules less permissive

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/aws-operator#99]
For now our Source/Destination `CidrIp` is `0.0.0.0/0`, it's too open

**Comment by asymmetric** [comment]
Here's what I think the `Source/Dest` rules should look like for each of the SGs we currently have:

## Masters SG

* G8S cluster
* Workers VPC

### Workers SG

* Customers, so `0.0.0.0`

**Comment by asymmetric** [comment]
[List](https://coreos.com/kubernetes/docs/latest/kubernetes-networking.html) of ports and sources.
